// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opgcudohhcpmmzvkivtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wZ2N1ZG9oaGNwbW16dmtpdnRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1MDc5NjQsImV4cCI6MjA4NzA4Mzk2NH0.qIOeXz8sh0PCWVSHw7BOHbP7sqWY_EBcOZKqJCYtZ6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});